// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IPostMigrationFactory$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IPostMigrationFactory";
  readonly sourceName: "contracts/interfaces/IPostMigrationFactory.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"curve","type":"address"}],"name":"authorizeCurve","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"address","name":"creator","type":"address"},{"internalType":"address","name":"referrer","type":"address"},{"internalType":"uint256","name":"tokenAmount","type":"uint256"}],"name":"createPool","outputs":[{"internalType":"address","name":"pool","type":"address"}],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"}],"name":"getPool","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"offset","type":"uint256"},{"internalType":"uint256","name":"limit","type":"uint256"}],"name":"getPools","outputs":[{"internalType":"address[]","name":"","type":"address[]"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"addr","type":"address"}],"name":"isPool","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"factory_","type":"address"}],"name":"setAuthorizedFactory","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IPostMigrationFactory.sol";
  readonly buildInfoId: "solc-0_8_24-faeab627b5924d47227edd308545b6689ffe02d5";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IPostMigrationFactory"]: IPostMigrationFactory$Type;
    ["contracts/interfaces/IPostMigrationFactory.sol:IPostMigrationFactory"]: IPostMigrationFactory$Type;
  }
}