// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ITokenFactory$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ITokenFactory";
  readonly sourceName: "contracts/interfaces/ITokenFactory.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"token","type":"address"}],"name":"isPaused","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"creator","type":"address"}],"name":"onArenaWin","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"token","type":"address"},{"internalType":"address","name":"pool","type":"address"}],"name":"onGraduation","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ITokenFactory.sol";
  readonly buildInfoId: "solc-0_8_24-09f59ff99871a1c50df726f3227da91cf885a75d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ITokenFactory"]: ITokenFactory$Type;
    ["contracts/interfaces/ITokenFactory.sol:ITokenFactory"]: ITokenFactory$Type;
  }
}